redis:
  cluster:
    enabled: false
  fullnameOverride: melo-redis
  networkPolicy:
    enabled: false
  master:
    persistence:
      enabled: false
  metrics:
    enabled: false
  podDisruptionBudget:
    enabled: false
  tls:
    enabled: false
  securityContext:
    enabled: false
  sentinel:
    enabled: false
  slave:
    persistence:
      enabled: false
  sysctlImage:
    enabled: false
  volumePermissions:
    enabled: false
  usePassword: false

mysql:
  db:
    password: "testpassword"
    name: "meloapp"
  fullnameOverride: melo-mysql
  initdbScripts:
    my_init_script.sh: |
      #!/bin/sh
      cat << EOF
      mysql -u root -ptestpassword -D meloapp -e \
      "CREATE TABLE TAG_TYPES (
        id INT NOT NULL,
        type VARCHAR(512) NOT NULL,
        PRIMARY KEY (id)
      );
      INSERT INTO TAG_TYPES (
        id,
        type
      ) VALUES (
        '1',
        'weather'
      );
      INSERT INTO TAG_TYPES (
        id,
        type
      ) VALUES (
        '2',
        'location'
      );
      INSERT INTO TAG_TYPES (
        id,
        type
      ) VALUES (
        '3',
        'mood'
      );
      CREATE TABLE TAGS (
        id INT NOT NULL,
        name VARCHAR(512) NOT NULL,
        type_id INT NOT NULL,
        value VARCHAR(512) NULL,
        PRIMARY KEY (id)
      );
      INSERT INTO TAGS (
        id,
        name,
        type_id
      ) VALUES (
        '1',
        'rainy',
        '1'
      );
      INSERT INTO TAGS (
        id,
        name,
        type_id
      ) VALUES (
        '2',
        'shomal',
        '2'
      );
      INSERT INTO TAGS (
        id,
        name,
        type_id
      ) VALUES (
        '3',
        'after-breakup',
        '3'
      );
      CREATE TABLE TAG_RELATIONS (
        id INT NOT NULL,
        tag_id INT NOT NULL,
        category VARCHAR(512) NOT NULL,
        category_id INT NOT NULL,
        PRIMARY KEY (id));
      INSERT INTO TAG_RELATIONS (
        id,
        tag_id,
        category,
        category_id
      ) VALUES (
        '1',
        '1',
        'song',
        '1'
      );
      INSERT INTO TAG_RELATIONS (
        id,
        tag_id,
        category,
        category_id
      ) VALUES (
        '2',
        '2',
        'song',
        '2'
      );
      INSERT INTO TAG_RELATIONS (
        id,
        tag_id,
        category,
        category_id
      ) VALUES (
        '3',
        '3',
        'album',
        '3'
      );"
      EOF
  master:
    persistence:
      enabled: false
    replication:
      enabled: false
    securityContext:
      enabled: false
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  replication:
    enabled: false
  slave:
    persistence:
      enabled: false
    securityContext:
      enabled: false
    replicas: 1
  volumePermissions:
    enabled: false

replicaCount: 1

image:
  repository: melo_tag
  pullPolicy: IfNotPresent
  # tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #     - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: localhost
      paths:
        - "/"
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  volumeMounts:
    mountPath: /app/.env
    subPath: .env
