# BEGIN project-specific configuration

.relation: &relation
  variables:
    MODULE_NAME: "relation"
    IMAGE_NAME: "melo_relation"
    DOCKERFILE: "apps/relation/docker/development/Dockerfile"
  only:
    changes:
    - "apps/relation/**/*"

# END project-specific configuration

# BEGIN actual pipeline definition

build:apps:relation:
  extends:
  - ".build"
  - ".relation"

test:apps:relation:
  dependencies:
  - "build:s:relation"
  extends:
  - ".test"
  - ".relation"

coverage:apps:relation:
  dependencies:
  - "test:apps:relation"
  extends:
  - ".coverage"
  - ".relation"

dockerization:apps:relation:
  dependencies:
  - "test:apps:relation"
  extends:
  - ".dockerization"
  - ".relation"

# END actual pipeline definition
