# BEGIN project-specific configuration

.melo-api: &melo-api
  variables:
    MODULE_NAME: melo-api
    IMAGE_NAME: melo-melo-api
    DOCKERFILE: apps/melo-api/docker/development/Dockerfile
  only:
    changes:
      - "apps/melo-api/**/*"

# END project-specific configuration

# BEGIN actual pipeline definition

build:apps:melo-api:
  extends:
    - .build
    - .melo-api

test:apps:melo-api:
  dependencies:
    - build:apps:melo-api
  extends:
    - .test
    - .melo-api

coverage:apps:melo-api:
  dependencies:
    - test:apps:melo-api
  extends:
    - .coverage
    - .melo-api

dockerization:apps:melo-api:
  dependencies:
    - build:apps:melo-api
  extends:
    - .dockerization
    - .melo-api

# END actual pipeline definition
