apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common/k8s
  - name: mysql
    version: 4.5.0
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 10.7.1
    repository: https://charts.bitnami.com/bitnami
description: A Helm chart for Kubernetes
name: at
type: application
version: 1.0.0
