kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaniko-cache-claim
  namespace: melo
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi
