import { LogLevel } from "@sentry/types";

export interface AppConfigServiceInterface {
  apmActive: boolean;
  apmLogLevel: string;
  apmSecretToken: string;
  apmServerUrl: string;
  apmServiceName: string;
  cacheHost: string;
  cacheMax: number;
  cachePort: number;
  cacheStore: string;
  cacheTTL: number;
  dgraphAddress: string;
  dgraphDebug: boolean;
  hashIdAlphabet: string;
  hashIdMinLength: number;
  hashIdSalt: string;
  hashIdSeps: string;
  mangooseRetryAttempts: number;
  mangooseRetryDelay: number;
  mangooseUri: string;
  port: number;
  promDefaultLabels: Record<string, string>;
  promDefaultMetricsEnabled: boolean;
  promPath: string;
  promPrefix: string;
  rateLimitMax: number;
  rateLimitWindowMs: number;
  sentryDebug: boolean;
  sentryDsn: string;
  sentryEnviroment: string;
  sentryLogLevel: LogLevel;
  sentryRelease: string;
  typeOrmDatabase: string;
  typeOrmHost: string;
  typeOrmLogging: boolean;
  typeOrmPassword: string;
  typeOrmPort: number;
  typeOrmSynchronize: boolean;
  typeOrmUsername: string;
}
