export const HTTP_REQUESTS_TOTAL = "http_requests_total";
export const PROM_CONFIGURATION_DEFAULT = "PROM_CONFIGURATION_DEFAULT";
export const PROM_CONFIGURATION_NAME = "PROM_CONFIGURATION";
export const PROM_METRIC = "PROM";
export const PROM_MODULE_OPTIONS = "PROM_MODULE_OPTIONS";
export const PROM_REGISTRY_DEFAULT = "PROM_REGISTRY_DEFAULT";
export const PROM_REGISTRY_NAME = "PROM_REGISTRY";
