apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: melo-at
profiles:
  - name: cluster
    build:
      artifacts:
        - image: gitlab-repo.3re.ir/melobit/melo-api/melo/at
          kaniko:
            dockerfile: docker/development/at.Dockerfile
          sync:
            infer:
              - "apps/at/**/*.*"
              - "libs/**/*.*"
              - "type/**/*.*"
      cluster:
        namespace: melo
        dockerConfig:
          secretName: kaniko-secret
        serviceAccount: kaniko-service-account
  - name: local
    build:
      artifacts:
        - image: melo/at
          docker:
            dockerfile: docker/development/at.Dockerfile
          sync:
            infer:
              - "apps/at/**/*.*"
              - "libs/**/*.*"
              - "type/**/*.*"
      tagPolicy:
        sha256: {}
      local:
        push: false
        useBuildkit: true
at:
  - image: melo/artist
    structureTests:
      - skaffold/structure-test/at/file-existence-test.yaml
      - skaffold/structure-test/at/global-env-var.yaml
deploy:
  helm:
    releases:
      - name: melo
        chartPath: k8s/at
        artifactOverrides:
          image: melo/at
        namespace: melo
        wait: true
    flags:
      install:
        - --create-namespace
      upgrade:
        - --atomic
