apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: melo-playlist
profiles:
  - name: cluster
    build:
      artifacts:
        - image: gitlab-repo.3re.ir/melobit/melo-api/melo/playlist
          kaniko:
            dockerfile: docker/development/playlist.Dockerfile
          sync:
            infer:
              - "apps/playlist/**/*.*"
              - "libs/**/*.*"
              - "type/**/*.*"
      cluster:
        namespace: melo
        dockerConfig:
          secretName: kaniko-secret
        serviceAccount: kaniko-service-account
  - name: local
    build:
      artifacts:
        - image: melo/playlist
          docker:
            dockerfile: docker/development/playlist.Dockerfile
          sync:
            infer:
              - "apps/playlist/**/*.*"
              - "libs/**/*.*"
              - "type/**/*.*"
      tagPolicy:
        sha256: {}
      local:
        push: false
        useBuildkit: true
test:
  - image: melo/playlist
    structureTests:
      - skaffold/structure-test/playlist/file-existence-test.yaml
      - skaffold/structure-test/playlist/global-env-var.yaml
deploy:
  helm:
    releases:
      - name: melo
        chartPath: k8s/playlist
        artifactOverrides:
          image: melo/playlist
        namespace: melo
        wait: true
    flags:
      install:
        - --create-namespace
      upgrade:
        - --atomic
